apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccine-api-gateway-app
  labels:
    app: vaccine-api-gateway-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vaccine-api-gateway-app
  template:
    metadata:
      labels:
        app: vaccine-api-gateway-app
    spec:
      containers:
        - name: vaccine-api-gateway-app
          image: bits/minikube-gateway
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: vaccine-api-gateway-svc
spec:
  selector:
    app: vaccine-api-gateway-app
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 32000
